fix(renderer): fix jumping to the top when opening files. Fixes #1025
nvim-neo-tree/neo-tree.nvim pull request #1274
Opened 2023-12-27 18:17 UTC by georgeguimaraes

When opening files you had to scroll down to find, the neo-tree window jumped to the top (see #1025).

This is because Neovim changed the way `nvim_buf_set_lines` works in https://github.com/neovim/neovim/commit/008154954791001efcc46c28146e21403f3a698b (https://github.com/neovim/neovim/pull/24824) and later in https://github.com/neovim/neovim/pull/24889

This change in Neovim caused some problems in plugins:
- https://github.com/nvim-telescope/telescope.nvim/issues/2667
- https://github.com/folke/which-key.nvim/pull/516

To ensure the window stays fixed, we have to use `winsaveview` and `winrestview` (wrapped in `M.position`) inside `render_tree`.

This fixed issue #1025. Although it still didn't fix #996.

2023-12-27 18:54 UTC, georgeguimaraes commented
Please @miversen33 can you try it and see if I made a mess?

2023-12-27 19:44 UTC, georgeguimaraes commented
I have a fix for #996 that builds on top of this PR. I'll have my commit cleaned up and I'll test a few edge cases and I'll update this PR

2023-12-27 19:58 UTC, georgeguimaraes commented
Ok, now [6e6c42f](https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1274/commits/6e6c42f6e4dec58dcb22ea735962404fd9f22ee3) fixes #996 as well. I've tested some cases with it, but I am not confident of such change, even though it uses well-established functions `winsaveview/winrestview`.

If you all feel more comfortable, I can remove this commit and we can just focus on #1025.

2023-12-27 20:40 UTC, miversen33 commented
I'll pull this down and review the branch and code this evening, I have a nice long drive ahead of me this afternoon

2023-12-28 03:34 UTC, miversen33 commented
I left some notes on this. The overall gist seems good though I will not be the one to sign off on this. I will leave that to either @pysan3  or @cseickel  as they are far more active in neo-tree core than myself. They will in theory be able to see potential side effects from this code that I might miss.

2023-12-28 04:42 UTC, pysan3 requested changes

2023-12-28 04:42 UTC, pysan3 commented on lua/neo-tree/ui/renderer.lua
> +      log.trace("win_state: " .. vim.inspect(win_state))
Just a minor pick; I don't think it is good to leave `vim.inspect` inside the codebase, as the log.debug below already gives good info.

2023-12-28 04:44 UTC, pysan3 commented
The change looks awesome on my end! Thanks a lot!

I'll pass it to @cseickel now.

2023-12-29 01:50 UTC, cseickel approved these changes
Looks reasonable to me and since @miversen33 and @pysan3 also reviewed I'll skip testing it myself.

Thanks!

2023-12-29 01:50 UTC, merged

2023-12-31 14:54 UTC, OliverChao commented
Sorry for mentioning that this pr seems breaking the `open` action in `Neotree reveal`.

Open one file and run `Neotree reveal`, then run `<cr>` to `open` the directory  of that file.

After running `<CR>`,  it jumps to the file location not toggle the directory.

2023-12-31 16:00 UTC, cseickel commented
> Sorry for mentioning that this pr seems breaking the `open` action in `Neotree reveal`.
> 
> Open one file and run `Neotree reveal`, then run `<cr>` to `open` the directory of that file.
> 
> After running `<CR>`, it jumps to the file location not toggle the directory.

That is true. Beyond that, any action you take will result in the previously revealed file being focused. That includes opening other files. Whatever the last revealed file is will be permanently stuck and refocused after every render.

I will make this a new issue.