feat(common): add `rename_basename command`
nvim-neo-tree/neo-tree.nvim pull request #1581
Opened 2024-10-12 09:27 UTC by dunix241

Implemented:
- command `rename_basename` that behaves analogously to `rename` while allowing to rename the node without the extension.

2024-11-24 16:07 UTC, cseickel commented
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1606

2024-12-15 22:43 UTC, pynappo requested changes
Overall looks good to me. if you don't mind waiting a bit I'll test out the PR after my final exams end on Tuesday, just to make sure this works as intended.

2024-12-15 22:43 UTC, pynappo commented on lua/neo-tree/defaults.lua
> +      ["b"] = "rename_basename",
Can you also add it here in the README as well: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/395ce4675a54828f9fd730d78f7910c114ab0a49/README.md?plain=1#L286

2024-12-15 22:43 UTC, pynappo commented on lua/neo-tree/sources/filesystem/lib/fs_actions.lua
> +      .. new_name
```suggestion
  local get_destination = function(new_base_name)
    return parent_path
      .. utils.path_separator
      .. new_base_name
```

2024-12-16 00:59 UTC, dunix241 commented
> Overall looks good to me. if you don't mind waiting a bit I'll test out the PR after my final exams end on Tuesday, just to make sure this works as intended.

Good luck with your exams! 😅
Hope you'll do well I don't mind waiting

2024-12-22 06:57 UTC, pynappo approved these changes

2024-12-22 07:03 UTC, merged