feat (fs_actions): add brace expansion for creating files / folders
nvim-neo-tree/neo-tree.nvim pull request #661
Opened 2022-12-17 18:20 UTC by pysan3

Hi, big thanks for the nice plugin again.

This PR aims to implement the brace expansion feature just like BASH (probly POSIX compatible?) shell as suggested in #647.

The core implementation is in `require("neo-tree.utils").brace_expand(s)` which handles all expansion and return a list of strings being expanded. If no expansion is found, it returns a one-element list with the raw input.

The calculation is not done by using the shell or anything and is just emulated inside lua, meaning that Windows users can also use this feature with the bash syntax.

## More Testing Needed!!

I am pretty sure I was able to cover all edge cases but it would be nice if anyone could double check if I hadn't screwed up anything.
The basic syntax of bash brace expansion can be found [here](https://effective-shell.com/part-6-advanced-techniques/understanding-shell-expansion/) or [here](https://facelessuser.github.io/bracex/) or by googling.

Here are some examples I checked myself.
| Input                    | Output                                                                                   |
| ------------------------ | ---------------------------------------------------------------------------------------- |
| `"x{a..e..2}"`           | `{ "xa", "xc", "xe" }`                                                                   |
| `"file.txt{,.bak}"`      | `{ "file.txt", "file.txt.bak" }`                                                         |
| `"./{a,b}/{00..02}.lua"` | `{ "./a/00.lua", "./a/01.lua", "./a/02.lua", "./b/00.lua", "./b/01.lua", "./b/02.lua" }` |

## README

I would be very happy if you could mention this feature in the README.

I do not know any other file explorer-like plugin in vim / neovim that has this feature and I think this would be a killing feature against the other options :)

Best,
pysan3

2022-12-24 07:36 UTC, etrnal70 commented
Hello, sorry for the late response. I'm daily driving it and it works great ! I'll try to find some more edge case this weekend

2022-12-24 15:07 UTC, cseickel approved these changes

2022-12-24 15:11 UTC, cseickel requested changes
I'm ready to merge this based on code and functionality, but I don't want to add to the documentation problem I already have by adding more undocumented features.

Can you please add some explanation to the help file?

You can also add it to the README if you want, or just reference the entry in the help file.

2022-12-26 12:09 UTC, pysan3 commented
> I'm daily driving it and it works great !

@etrnal70 Thanks for testing!

> Can you please add some explanation to the help file?
> You can also add it to the README if you want, or just reference the entry in the help file.

@cseickel I have added some documentation for the brace expansion feature in the help file and README.

2022-12-26 14:44 UTC, cseickel approved these changes

2022-12-26 14:44 UTC, cseickel commented
Look good @pysan3, thanks!

2022-12-26 14:45 UTC, merged